// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrndfnxllyxqeeukpyir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndybmRmbnhsbHl4cWVldWtweWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Njg0NzUsImV4cCI6MjA2MzA0NDQ3NX0.swbKlKVlioGKVCRUVVRfqSAsSLwL6KdmEIiRmCuLcMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);